"""
The predictor: signals, model and base rate combined into one probability.

## What this is for

The agent's thesis is generated by a language model reading a macro brief.
Left alone, that model has no way to know whether the yield curve has
actually predicted anything on this data, and it will write confident prose
either way. This module produces a **quantitative prior** -- a probability
with a stated provenance -- that goes into the prompt alongside the brief, and
that the thesis is measured against afterwards.

## The three sources, and how they are weighted

    base rate   the historical frequency of the target rising over the
                horizon. Always available. Weight: whatever is left over.

    signals     the composite of the signal readings, each weighted by the
                IC it has actually demonstrated (``SignalScorecard``). A
                signal with no measured edge contributes nothing.

    model       the winner of the walk-forward comparison -- network,
                logistic, or neither.

Weights are **not** hyperparameters. Each source's weight is proportional to
how much it beat the base rate by, out of sample, and a source that did not
beat the base rate gets zero. When nothing beat the base rate, the prediction
IS the base rate, at full weight, and the report says so.

That is the property worth defending: this module cannot produce a confident
number from components that have not earned it. The failure mode it is built
against is the ensemble that averages three unvalidated models and reports
the average as though the averaging conferred reliability.

## Shrinkage

The combined probability is shrunk toward the base rate by a factor that
depends on the total demonstrated skill. With no skill the shrinkage is
total. This is what keeps the prior from being wrong AND loud in exactly the
situation where it knows least.
"""

from __future__ import annotations

import json
import logging
import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping

from vault.data.series import Series
from vault.nn.dataset import Standardiser
from vault.nn.network import MLP
from vault.nn.train import LogisticModel, TrainingReport
from vault.signals.library import SIGNALS, evaluate_all
from vault.signals.scoring import SignalScorecard
from vault.signals.types import SignalReading

logger = logging.getLogger(__name__)

__all__ = ["Prediction", "Predictor"]

# A source must beat the base rate by at least this much Brier to be given
# any weight. Below it, the difference is noise at these sample sizes.
MIN_EDGE = 0.005


@dataclass(slots=True)
class Prediction:
    """A probability, and a full account of where it came from."""

    probability: float
    base_rate: float

    from_signals: float | None = None
    from_model: float | None = None

    weight_signals: float = 0.0
    weight_model: float = 0.0
    weight_base: float = 1.0

    shrinkage: float = 1.0
    confidence: str = "none"
    provenance: str = ""

    contributions: list[dict[str, Any]] = field(default_factory=list)
    signals_used: int = 0
    signals_available: int = 0

    @property
    def edge(self) -> float:
        """Distance from the base rate. The part that is a claim."""
        return self.probability - self.base_rate

    def to_dict(self) -> dict[str, Any]:
        return {
            "probability": round(self.probability, 4),
            "base_rate": round(self.base_rate, 4),
            "edge": round(self.edge, 4),
            "from_signals": (
                round(self.from_signals, 4) if self.from_signals is not None else None
            ),
            "from_model": (
                round(self.from_model, 4) if self.from_model is not None else None
            ),
            "weights": {
                "signals": round(self.weight_signals, 4),
                "model": round(self.weight_model, 4),
                "base_rate": round(self.weight_base, 4),
            },
            "shrinkage": round(self.shrinkage, 4),
            "confidence": self.confidence,
            "provenance": self.provenance,
            "signals_used": self.signals_used,
            "signals_available": self.signals_available,
            "contributions": self.contributions,
        }

    def explain(self) -> str:
        lines = [
            f"P(up) = {self.probability:.3f} against a base rate of "
            f"{self.base_rate:.3f} ({self.edge:+.3f})",
            f"  confidence: {self.confidence}",
            f"  {self.provenance}",
        ]
        if self.contributions:
            lines.append("  top contributors:")
            for item in self.contributions[:5]:
                lines.append(
                    f"    {item['signal']:24s} strength {item['strength']:+.3f} "
                    f"x weight {item['weight']:.3f} = {item['contribution']:+.4f}"
                )
        return "\n".join(lines)


class Predictor:
    """Holds everything learned, and turns a series universe into a prior."""

    def __init__(self) -> None:
        self.scorecard: SignalScorecard | None = None
        self.report: TrainingReport | None = None
        self.model: MLP | LogisticModel | None = None
        self.model_kind: str = "none"
        self.scaler: Standardiser = Standardiser()
        self.base_rate: float = 0.5
        self.feature_names: list[str] = []

        self._weight_signals = 0.0
        self._weight_model = 0.0

    # -- fitting -----------------------------------------------------------

    def adopt(
        self,
        *,
        scorecard: SignalScorecard | None,
        report: TrainingReport | None,
        model: MLP | LogisticModel | None,
        scaler: Standardiser | None,
        base_rate: float,
        feature_names: list[str],
    ) -> None:
        """
        Take the fitted pieces and derive the blend weights from what each
        demonstrated -- never from a configured constant.
        """
        self.scorecard = scorecard
        self.report = report
        self.model = model
        self.scaler = scaler or Standardiser()
        self.base_rate = base_rate
        self.feature_names = feature_names
        self.model_kind = (
            report.winner if report and report.usable else "none"
        )

        # Model weight: how far it beat the base rate, out of sample.
        model_edge = 0.0
        if report and report.usable:
            best = min(report.brier_logistic, report.brier_network)
            model_edge = max(0.0, report.brier_base - best)
        if model_edge < MIN_EDGE or model is None:
            model_edge = 0.0

        # Signal weight: the total IC actually earned across signals. An IC of
        # 0.05 is a real macro signal; summing a few of them and capping keeps
        # this on the same scale as the model edge.
        signal_edge = 0.0
        if scorecard:
            signal_edge = min(0.05, sum(p.weight for p in scorecard.earning) * 0.2)

        total = model_edge + signal_edge
        if total <= 0:
            self._weight_signals = 0.0
            self._weight_model = 0.0
            return

        # Cap the combined non-base weight. Even a demonstrably skilful blend
        # does not get to override the base rate entirely on a sample this
        # size -- the cap is the shrinkage prior, made explicit.
        cap = min(0.60, total * 8.0)
        self._weight_model = cap * (model_edge / total)
        self._weight_signals = cap * (signal_edge / total)

    # -- predicting --------------------------------------------------------

    def predict(self, series: Mapping[str, Series]) -> Prediction:
        readings = evaluate_all(series)
        available = sum(1 for r in readings if r.usable)

        signal_probability, contributions, used = self._from_signals(readings)
        model_probability = self._from_model(readings)

        weight_signals = self._weight_signals if signal_probability is not None else 0.0
        weight_model = self._weight_model if model_probability is not None else 0.0
        weight_base = max(0.0, 1.0 - weight_signals - weight_model)

        probability = weight_base * self.base_rate
        if signal_probability is not None:
            probability += weight_signals * signal_probability
        if model_probability is not None:
            probability += weight_model * model_probability

        shrinkage = 1.0 - weight_base
        confidence = (
            "none" if shrinkage <= 0.0 else
            "low" if shrinkage < 0.15 else
            "moderate" if shrinkage < 0.35 else
            "meaningful"
        )

        prediction = Prediction(
            probability=min(0.95, max(0.05, probability)),
            base_rate=self.base_rate,
            from_signals=signal_probability,
            from_model=model_probability,
            weight_signals=weight_signals,
            weight_model=weight_model,
            weight_base=weight_base,
            shrinkage=shrinkage,
            confidence=confidence,
            contributions=contributions,
            signals_used=used,
            signals_available=available,
        )
        prediction.provenance = self._provenance(prediction)
        return prediction

    def _from_signals(
        self, readings: list[SignalReading]
    ) -> tuple[float | None, list[dict[str, Any]], int]:
        if not self.scorecard or not self.scorecard.earning:
            return None, [], 0

        weights = self.scorecard.weights
        total_weight = 0.0
        total = 0.0
        contributions: list[dict[str, Any]] = []

        for reading in readings:
            weight = weights.get(reading.key, 0.0)
            if weight <= 0 or not reading.usable:
                continue
            contribution = reading.weighted_strength * weight
            total += contribution
            total_weight += weight
            contributions.append({
                "signal": reading.key,
                "strength": round(reading.weighted_strength, 4),
                "weight": round(weight, 4),
                "contribution": round(contribution, 5),
            })

        if total_weight <= 0:
            return None, [], 0

        # Map the weighted-average strength in [-1, 1] onto a probability
        # around the base rate. The 0.25 scale means a fully saturated
        # composite moves the probability by 25 points, which is already an
        # aggressive claim for a macro signal.
        average = total / total_weight
        probability = self.base_rate + 0.25 * average
        contributions.sort(key=lambda item: -abs(item["contribution"]))
        return min(0.95, max(0.05, probability)), contributions, len(contributions)

    def _from_model(self, readings: list[SignalReading]) -> float | None:
        if self.model is None or self.model_kind == "none":
            return None
        features = [
            reading.weighted_strength if reading.usable else 0.0
            for reading in readings
        ]
        if len(features) != len(self.feature_names):
            logger.warning(
                "feature count changed (%d now, %d at fit); the model cannot "
                "be applied", len(features), len(self.feature_names),
            )
            return None
        scaled = self.scaler.transform([features])[0]
        return self.model.predict_one(scaled)

    def _provenance(self, prediction: Prediction) -> str:
        if prediction.weight_base >= 1.0:
            return (
                "Nothing has demonstrated an edge, so this is the base rate "
                "and nothing else. No signal earned weight and no model beat "
                "the base rate out of sample."
            )
        parts = []
        if prediction.weight_signals > 0 and self.scorecard:
            parts.append(
                f"{len(self.scorecard.earning)} signal(s) with measured IC "
                f"at weight {prediction.weight_signals:.0%}"
            )
        if prediction.weight_model > 0 and self.report:
            parts.append(
                f"the {self.model_kind} model "
                f"(out-of-sample Brier "
                f"{min(self.report.brier_logistic, self.report.brier_network):.4f} "
                f"against {self.report.brier_base:.4f} for the base rate) at "
                f"weight {prediction.weight_model:.0%}"
            )
        return (
            "Blended from " + " and ".join(parts)
            + f", with the remaining {prediction.weight_base:.0%} on the base rate."
        )

    # -- persistence -------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "model_kind": self.model_kind,
            "base_rate": self.base_rate,
            "feature_names": self.feature_names,
            "weights": {
                "signals": round(self._weight_signals, 4),
                "model": round(self._weight_model, 4),
                "base_rate": round(
                    max(0.0, 1 - self._weight_signals - self._weight_model), 4),
            },
            "scaler": self.scaler.to_dict(),
            "scorecard": self.scorecard.to_dict() if self.scorecard else None,
            "training": self.report.to_dict() if self.report else None,
            "model": (
                self.model.to_dict()
                if isinstance(self.model, MLP)
                else ({"w": self.model.w, "b": self.model.b}
                      if isinstance(self.model, LogisticModel) else None)
            ),
        }

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")

    def summary(self) -> str:
        if self.model_kind == "none" and not (
            self.scorecard and self.scorecard.earning
        ):
            return (
                "Predictor: untrained, or trained and found nothing. Every "
                "prediction is the base rate."
            )
        earning = len(self.scorecard.earning) if self.scorecard else 0
        return (
            f"Predictor: {earning} earning signal(s) at "
            f"{self._weight_signals:.0%}, {self.model_kind} model at "
            f"{self._weight_model:.0%}, base rate at "
            f"{max(0.0, 1 - self._weight_signals - self._weight_model):.0%}"
        )
